---
user: user1
application_name: agent
namespace: agent-user1

git_url: https://gitea.apps.cluster-kd7wl.dynamic.redhatworkshops.io/user1/mcp.git
git_revision: main
git_subdirectory: agent
registry: image-registry.openshift-image-registry.svc:5000
agent_endpoint: http://agent.agent-user1.svc:8000/report-failure

# Agent Configuration
agentConfig:
  litellm_url: "FROM SECRETS"
  litellm_api_key: "FROM SECRETS"
  litellm_model: "FROM SECRETS"
  mcp_openshift_url: https://mcp-openshift-mcp-user1.svc.cluster.local:8080/sse#openshift
  mcp_openshift_transport: sse
  mcp_gitea_url: https://mcp-gitea-mcp-user1.svc.cluster.local:8080/mcp
  mcp_gitea_transport: streamable-http
  port: 8000

# Service Account configuration
serviceAccount:
  name: pipeline

# Role Binding configuration
roleBinding:
  name: openshift-pipelines-edit
  clusterRole: edit

# Job configuration
job:
  name: trigger-agent-service-build
  enabled: true

# Pipeline configuration
pipeline:
  name: agent-service-build
  timeout: 1h0m0s

# Workspace configuration
workspace:
  name: workspace
  storage: 3Gi

# Container images
images:
  cliTool: registry.redhat.io/openshift4/ose-cli:latest
