---
user: user1
application_name: agent
namespace: agent-user1
registry: image-registry.openshift-image-registry.svc:5000
git_url: https://gitea.apps.cluster-kd7wl.dynamic.redhatworkshops.io/user1/mcp.git
git_revision: main
git_subdirectory: agent
agent_endpoint: http://agent.agent-user1.svc:8000/report-failure

# Agent Configuration
agentConfig:
  litellm_url: https://litellm-litemaas.apps.prod.rhoai.rh-aiservices-bu.com/v1
  litellm_api_key: sk-Z9kMTaKyZOE5NPShqPhzOg
  litellm_model: openai/Llama-4-Scout-17B-16E-W4A16
  mcp_openshift_url: https://mcp-openshift-mcp-user1.apps.cluster-kd7wl.dynamic.redhatworkshops.io/sse#openshift
  mcp_openshift_transport: sse
  mcp_gitea_url: https://mcp-gitea-mcp-user1.apps.cluster-kd7wl.dynamic.redhatworkshops.io/mcp
  mcp_gitea_transport: streamable-http
  port: 8000

# Service Account configuration
serviceAccount:
  name: pipeline

# Role Binding configuration
roleBinding:
  name: openshift-pipelines-edit
  clusterRole: edit

# Job configuration
job:
  name: trigger-agent-service-build
  enabled: true

# Pipeline configuration
pipeline:
  name: agent-service-build
  timeout: 1h0m0s

# Workspace configuration
workspace:
  name: workspace
  storage: 3Gi

# Container images
images:
  cliTool: registry.redhat.io/openshift4/ose-cli:latest
